name: ESLint

on:
  push:
    branches:
      - main
      - cibranch
  pull_request:
    branches:
      - main
      - cibranch
  schedule:
    - cron: "40 18 * * 1"

jobs:
  eslint:
    name: Run ESLint Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Ajustar permissões do ESLint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Rodar ESLint com arquivo eslint.config.mjs
        run: ./node_modules/.bin/eslint . --config eslint.config.mjs --ext .js,.mjs,.cjs
