name: CI/CD - ESLint + Testes + Deploy React

on:
  push:
    branches:
      - main
      - cibranch
  pull_request:
    branches:
      - main
      - cibranch
  schedule:
    - cron: "40 18 * * 1"

jobs:
  eslint:
    name: Run ESLint Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Ajustar permissões do ESLint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Rodar ESLint com arquivo eslint.config.mjs
        run: ./node_modules/.bin/eslint . --config eslint.config.mjs --ext .js,.mjs,.cjs

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

  deploy:
    name: Deploy React App para GitHub Pages
    runs-on: ubuntu-latest
    needs: [eslint, tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
