name: ESLint

on:
  push:
    branches: ["main", "cibranch"]
  pull_request:
    branches: ["main", "cibranch"]
  schedule:
    - cron: "40 18 * * 1" # Todos os lunes às 18:40

jobs:
  eslint:
    name: Run ESLint Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          npx eslint . \
          --config .eslintrc.js \
          --ext .js,.jsx,.ts,.tsx
